"""
Django settings for toggle_project project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lwx26s*_alvqu3hyo01mq028b1c$b__6d4^6#pdm!oc2zto&fa'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'toggle_app',
]

JAZZMIN_SETTINGS = {
    "site_title": "My Admin Panel",  # Title of the site
    "site_header": "My Admin Dashboard",  # Header text
    "site_brand": "My Brand",  # Branding name
    "site_logo": None,  # Optional logo image
    "welcome_sign": "Welcome to My Admin Panel",  # Welcome message
    "topmenu_links": [  # Top menu links
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Project", "url": "/", "new_window": True},
    ],
    "show_sidebar": True,  # Show or hide sidebar
    "navigation_expanded": True,  # Automatically expand the menu
    "user_avatar": None,  # Use a user avatar
    "custom_css": None,  # Custom CSS (optional)
    "custom_js": None,  # Custom JS (optional)
    "hide_apps": [],  # List of apps to hide from the menu
    "hide_models": [],  # List of models to hide
    "order_with_respect_to": ["auth", "toggle_app"],  # Order of apps/models
}

# JAZZMIN_SETTINGS["icons"] = {
#     "auth": "fas fa-users-cog",  # Example: User icon for the 'auth' app
#     "auth.User": "fas fa-user",  # Icon for the 'User' model
#     "toggle_app.ToggleItem": "fas fa-toggle-on",  # Custom icon for a model
# }

# JAZZMIN_UI_TWEAKS = {
#     "theme": "cosmo",  # Choose a built-in Bootstrap theme
#     # "dark_mode_theme": "darkly",  # Optional dark mode theme
#     "navbar_small_text": False,
#     "footer_fixed": True,
#     "sidebar_fixed": True,
#     "button_classes": {
#         "primary": "btn-outline-primary",
#         "secondary": "btn-outline-secondary",
#     },
# }

# JAZZMIN_UI_TWEAKS["theme"] = "litera"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'toggle_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'toggle_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
